### ISSUE TITLE
BluePay Card Expiration Error

### ISSUE THREAD

**Issue by bizarro5** [sc0ttkclark/gravity-forms-bluepay#1]
Greetings,

First of all, thank you for the BluePay plugin for Gravity Forms. Everything is perfect with the exception of the expiration date. I keep getting "Expiration date required for CREDIT".

I checked the code and changed the expire field to the same as BluePay's, but still received the same error.

Any help would be GREATLY appreciated!

**Comment by sc0ttkclark** [comment]
This was fixed a few days after the report, not sure why I didn't close it back then.
